### ISSUE TITLE
How to run easy-sauce in node < 6

### ISSUE THREAD

**Issue by daveashworth** [philipwalton/easy-sauce#2]
In my package.json file I have the test script set to `easy-sauce`:

```
{
  "scripts": {
    "test": "easy-sauce"
  }
}
```

And in node environment 5.6, I get the following error when trying to run `npm test`:

```
/data/projects/personal/easytest/node_modules/easy-sauce/lib/cli.js:114
function formatResult(result = {}) {
                             ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/data/projects/personal/easytest/node_modules/easy-sauce/bin/easy-sauce:6:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

Works fine in node 6, but in the project I'd like to use this in, we can't use node 6 yet. What's the best way to resolve this?

**Comment by philipwalton** [comment]
If people want node 5 support, I suppose I could consider removing the es2015 code.

**Comment by daveashworth** [comment]
@philipwalton I can close this issue as I _just_ resolved the last issues keeping me from moving the project to node 6. So don't remove the es2015 code on my behalf 😃

Great job on `easy-sauce` btw. It really does make interacting with saucelabs... easy!

**Comment by philipwalton** [comment]
Thanks! Also, feel free to keep it open and we'll see if anyone else chimes in.
